### ISSUE TITLE
Reduntat tag

### ISSUE THREAD

**Issue by Adaste154** [MicrosoftDocs/azure-docs.pl-pl#42]
&lt;span style="background-color: yellow"&gt;

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 10ac4344-e048-21ab-7f4b-cdf806070780
* Version Independent ID: dbdcd1b9-86ef-75ab-5002-b5793b0292e2
* Content: [Usługa połączona jak diagnozować błędy w usłudze Azure Active Directory](https://docs.microsoft.com/pl-pl/azure/active-directory/develop/vs-active-directory-error)
* Content Source: [articles/active-directory/develop/vs-active-directory-error.md](https://github.com/MicrosoftDocs/azure-docs.pl-pl/blob/live/articles/active-directory/develop/vs-active-directory-error.md)
* Product: **visual-studio-dev15**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by CeciAc** [comment]
Hello, @Adaste154
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #17432](https://github.com/MicrosoftDocs/azure-docs/issues/17432) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Adaste154

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/17432.

We truly appreciate your contribution to our articles.
