### ISSUE TITLE
Azure CLI scripts do not copy tags properly when tag (or tag's value) contains spaces

### ISSUE THREAD

**Issue by siudeks** [MicrosoftDocs/azure-docs.pl-pl#469]
Azure CLI scripts on the page are working well for single-word tags and values. For instance, when tag=value is abc=def (abc - tag name, def - tag value) - scripts are working well.
In case when spaces are in tag - like a b c=d e f, tags from resource group to resources are copied partially.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: bc003943-8bc8-10ac-e633-5640cff3c397
* Version Independent ID: f8826361-f601-acf9-3e3d-c96579c02093
* Content: [Tagi zasobów dla organizacji logicznej](https://docs.microsoft.com/pl-pl/azure/azure-resource-manager/resource-group-using-tags)
* Content Source: [articles/azure-resource-manager/resource-group-using-tags.md](https://github.com/MicrosoftDocs/azure-docs.pl-pl/blob/master/articles/azure-resource-manager/resource-group-using-tags.md)

**Comment by srvbpigh** [comment]
Hello, @siudeks
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @siudeks

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43763

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
