### ISSUE TITLE
Is there no functionality to block any payment whatsoever?

### ISSUE THREAD

**Issue by Coolerhino** [MicrosoftDocs/azure-docs.pl-pl#474]
For example, disable resources that cost cash? I want to make sure that i learn azure and use only free services/quota. For students and poor people

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: caadbfdd-05b5-dc2e-7fd6-69ff2f9fb2e9
* Version Independent ID: f76cad32-0690-b06f-4447-0626b92d3e1f
* Content: [Unikanie naliczania opłat za korzystanie z bezpłatnego konta platformy Azure](https://docs.microsoft.com/pl-pl/azure/cost-management-billing/manage/avoid-charges-free-account#feedback)
* Content Source: [articles/cost-management-billing/manage/avoid-charges-free-account.md](https://github.com/MicrosoftDocs/azure-docs.pl-pl/blob/master/articles/cost-management-billing/manage/avoid-charges-free-account.md)
* Service: **cost-management-billing**
* GitHub Login: @amberbhargava
* Microsoft Alias: **banders**

**Comment by srvbpigh** [comment]
Hello, @Coolerhino
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54025](https://github.com/MicrosoftDocs/azure-docs/issues/54025) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Coolerhino, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54025. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
