### ISSUE TITLE
case sensitive properties names in angular js

### ISSUE THREAD

**Issue by jimiwal** [MicrosoftDocs/azure-docs.pl-pl#475]
Hi, In index.cshtml .Key, .Value properties should be uppercase.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: c0d03b4f-4157-0d04-0f48-0a3e2fb966cb
* Version Independent ID: 6b7bed89-eb53-105a-7971-476ddd4cf3b7
* Content: [Tworzenie aplikacji .NET na Service Fabric na platformie Azure](https://docs.microsoft.com/pl-pl/azure/service-fabric/service-fabric-tutorial-create-dotnet-app#feedback)
* Content Source: [articles/service-fabric/service-fabric-tutorial-create-dotnet-app.md](https://github.com/MicrosoftDocs/azure-docs.pl-pl/blob/master/articles/service-fabric/service-fabric-tutorial-create-dotnet-app.md)
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @jimiwal
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @jimiwal 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged. 

Please review issue https://github.com/MicrosoftDocs/azure-docs/issues/45162
For this reason we are closing this issue since it is duplicated. 


Kind regards, 

Microsoft DOCS International Team
